# Base configs
baseurl: "https://testing.aarontakespictures.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Aaron Takes Pictures"
# subtitle: "See the world through my eyes!"
author: "Aaron"
header:
 title: "Aaron"
 subtitle: "Takes Pictures"
footer:
 name: "Hey there, my name is Aaron"
 bio: "I'm a little teapot and I don't know what I'm doing."
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/aarontakespicsok/"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
